### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by salvatore373** [gerardobort/node-corenlp#13]
I just installed `corenlp` from `npm` and copied the extracted .zip file downloaded from "https://stanfordnlp.github.io/CoreNLP/download.html" in the corenlp folder in my project root.

When first running my code (that I pasted below), executing the first line, the following error occurs:

    `ReferenceError: regeneratorRuntime is not defined 
    at [MY-MODULE-ROOT]\node_modules\corenlp\dist\simple\annotable.js:112:36
    at [MY-MODULE-ROOT]\node_modules\corenlp\dist\simple\annotable.js:142:6
    at Object.<anonymous> ([MY-MODULE-ROOT]\node_modules\corenlp\dist\simple\annotable.js:146:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([MY-MODULE-ROOT]\node_modules\corenlp\dist\simple\document.js:9:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([MY-MODULE-ROOT]\node_modules\corenlp\dist\index.js:7:17` 

This is my code (the same of the README example): 

    `var CoreNLP = require('corenlp').default;
    
    CoreNLP.setup('English');
    const sent = new CoreNLP.simple.Sentence("I eat an apple.");
    sent.applyAnnotator(CoreNLP.simple.annotator.ParserAnnotator)
    .then(() => {
        console.log("This is sent.words(): ", JSON.stringify(sent.words()));
    })
    .catch((reason) => console.error(reason) );`

How can I fix it? Should I modify the corenlp module?

**Comment by tmclouisluk** [comment]
same here

**Comment by salvatore373** [comment]
I fixed it by adding `babel-polyfill` to the corenlp module dependencies and requiring it in the [MY-MODULE-ROOT]\node_modules\corenlp\dist\simple\annotable.js file

**Comment by azmainamin** [comment]
I get an error saying that CoreNLP.setup() is not a function. Did the syntax change?

**Comment by huhk-sysu** [comment]
A similar solution without editing the package's file.

```bash
npm install babel-register babel-polyfill --save-dev
```

in index.js
```javascript
require('babel-register');
require("babel-polyfill");
require('./app')
```

in app.js
```javascript
import CoreNLP, { Properties, Pipeline } from 'corenlp';
......
// the same as the README example.
```
