### ISSUE TITLE
Adding 'sentiment' to annotators throws an exception

### ISSUE THREAD

**Issue by azmainamin** [gerardobort/node-corenlp#27]
I am not sure if sentiment analysis is supported by corenlp.

`var nlp = require("corenlp").default;
var prop = require("./../node_modules/corenlp/dist/properties");
var pipe = require("./../node_modules/corenlp/dist/pipeline");
var sentence = require("./../node_modules/corenlp/dist/simple/sentence");
var tree = require("./../node_modules/corenlp/dist/util/tree");

const props = new prop.Properties({
  annotators: 'tokenize,ssplit,pos,lemma,ner,parse, sentiment',
});
const pipeline = new pipe.Pipeline(props, 'English'); // uses ConnectorServer by default

const sent = new sentence.Sentence('The little dog runs so fast.');
pipeline.annotate(sent)
  .then(sent => {
    console.log('parse', sent.parse());
    console.log(tree.Tree.fromSentence(sent).dump());
  })
  .catch(err => {
    console.log('err', err);
  });`

ERROR:

` err TypeError: Cannot read property 'toString' of undefined
    at Sentence.addAnnotator (/home/ubuntu/workspace/sentiment-analyzer/node_modules/corenlp/dist/simple/annotable.js:72:33)
    at /home/ubuntu/workspace/sentiment-analyzer/node_modules/corenlp/dist/simple/annotable.js:86:22
    at Array.forEach (native)
    at Sentence.addAnnotators (/home/ubuntu/workspace/sentiment-analyzer/node_modules/corenlp/dist/simple/annotable.js:85:18)
    at Pipeline._callee$ (/home/ubuntu/workspace/sentiment-analyzer/node_modules/corenlp/dist/pipeline.js:156:27)
    at tryCatch (/home/ubuntu/workspace/sentiment-analyzer/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/ubuntu/workspace/sentiment-analyzer/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.forEach.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/sentiment-analyzer/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/ubuntu/workspace/sentiment-analyzer/node_modules/corenlp/dist/pipeline.js:71:191)
    at /home/ubuntu/workspace/sentiment-analyzer/node_modules/corenlp/dist/pipeline.js:71:361`

**Comment by azmainamin** [comment]
Sentiment analysis is not supported yet.
